### ISSUE TITLE
Is there a way to use text field?

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookresearch/dlrm#10]
Hi,

Is there an easy way to leverage text data (words ID) in this model?
Categorical data extraction as done in the `convertUStringToDistinctInts` doesn't seem to be usable for text.

**Comment by hjmshi** [comment]
The `convertUStringToDistinctInts` function is used specifically for preprocessing the public Criteo Ad datasets (Kaggle and Terabyte). In order to use DLRM with text data, you would have to either preprocess your text dataset yourself or modify the `convertUStringToDistinctInts` function in order to generate the indices for your embedding lookups.

**Comment by pommedeterresautee** [comment]
Tks for your answer. 
I understand that you are advising a simple bag of words approach.
Is it something you have tested? Like using the recsys on content having as main meta data textual fields like Title/Description?
I ask as the paper only cite 2 public datasets where fields are not described.

**Comment by hjmshi** [comment]
As far as I understand your question, DLRM does not handle any textual fields and is only designed to handle datasets where the categories are well-defined, as in the Criteo Ad datasets.

**Comment by mnaumovfb** [comment]
It seems that this question has been answered. Closing.
