### ISSUE TITLE
meanings of dense features/embedding tables

### ISSUE THREAD

**Issue by sungjuryu** [facebookresearch/dlrm#105]
Hi, thanks for giving useful and interesting works.

While doing my study regarding recommendation systems (especially DLRM), it was very hard for me to clearly understand the meanings of a dense feature and embedding tables. I searched the web to find out their meaning, but there are few materials about them. Would you mind if you help me to understand the meaning of the input dense features and embedding tables? So, my questions are as follows.

1) (a-1) As far as I know, embedding tables hold some categorical data. For example, embedding tables 0/1/2 indicate movie/music/car, respectively. Is it right? 
Otherwise, (a-2) does each table indicate a category such as a non-specific category which humans cannot recognize in a specific word such as movie/music/car?
Moreover, (b-1) assuming that each embedding table holds ‘n’(=the number of rows in each embedding table) entries, do the entries indicate specific movie titles? For example, in the embedding table 0 which holds embedding vectors regarding movies, entry(=row) 0 holds an embedding vector about movie ‘Parasite’, entry 1 holds an embedding vector about movie ‘Harry Potter’, and entry 2 holds an embedding vector about movie ‘Star Wars’, and so on. Is it right? 
Otherwise, (b-2) do the entries only illustrate categories of the movies (not the specific titles) such as Fantasy, Action, Comedy, and so on? Or, do they have any other meanings?

2) Furthermore, do dense features illustrate non-sparse user data such as birthday, nationality, and etc (in contrary to the sparse indices which illustrate sparse user data) and the characteristic data of the input bench? (for example, if we use an advertisement model, part of the dense features illustrates the characteristics of each single advertisement.) 

3) (a-1) Assuming that embedding table 0 is related to the movie category (if question 1-b-1 is right) and the number of movies/music is getting larger because a lot of movies/music are released each week, does the row/size of the embedding tables also get larger? For example, the number of rows of the embedding table 0 (related to the movie) is 1000 in this week because 1000 movies have been released in this week. If 50 movies are released next week, the number of rows of the embedding table 0 becomes 1050 in the next week. Is it right? 
(a-2) Otherwise, is the #row/size of the embedding tables fixed although many movies/music are released over and over?

Thank you in advance!

**Comment by mnaumovfb** [comment]
Let me try to answer your questions below:

1. I usually think of a sparse feature as an index (or a set of indices), that correspond to an item. It is often helpful to embed this index/item into real d-dimensional space R^d because it provides an abstract representation of the item. Notice that the representation is learned during training. The collection of such embedding representations (vectors) is the embedding table.

2. I usually think of a dense feature as a floating point number that can represent an arbitrary input. You can feed anything to it. 

3. The embedding tables can change over time. However, DLRM provides a mechanism for capping their size `--max-ind-range=<number>` which caps the size and mods all indices into the given range.

You will find further examples in the following issue https://github.com/facebookresearch/dlrm/issues/22

Also, please take a look at my talk "Training Deep Learning Recommendation Models" at the PeRSonAI Tutorial at ASPLOS 2020. It should give you additional background and references about the subject.
https://personal-tutorial.com/personal-at-asplos-2020/

**Comment by sungjuryu** [comment]
Thank you for your kind reply.

I have one more question.

Let’s assume that embedding table 0 has 1000 entries now, but the number of the entries becomes 1050 in a few days.
In this case, a) are all the weights in the embedding table 0 fine-tuned during the re-training process? or b) are all the weights trained from scratch during the time?

Thank you so much!

**Comment by mnaumovfb** [comment]
There are many different approaches that work better in different circumstances. I think that we have addressed some of these questions in in section 2 of the "Bandana: Using Non-volatile Memory for Storing Deep Learning Models" paper https://arxiv.org/abs/1811.05922. Please take a look at it.

**Comment by sungjuryu** [comment]
Thank you for your quick response.

Your comments have been very helpful to me!

**Comment by mnaumovfb** [comment]
It seems that this issue is resolved. Closing.
