### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by kuatroka** [facebookresearch/dlrm#131]
Hi, thanks for the framework. It's still a bit difficult to clearly understand how it works. Are you aware of any sample code or jupyter notebook tutorial with end to end steps on how to use it with a custom or existing data set. For example using user's search query as user metadata and based on that query recommend the best possible paragraph or sentence from the data set?

Thanks

**Comment by mnaumovfb** [comment]
In order to get more background about the model you can read the reference [paper](https://arxiv.org/abs/1906.00091) and watch the following KDD [tutorial ](https://www.youtube.com/playlist?list=PL_lsbAsL_o2Cw0VXQ4Gd8B_5WUmZqQuIM).

We do not have an example jupyter notebook, but you can find the scripts to run the code in the ./test and ./bench directories. In order to run the latter scripts please follow the instructions for interfacing it with datasets in the README.

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.
