### ISSUE TITLE
Error generating torchscript dlrm model 

### ISSUE THREAD

**Issue by nithin-nod** [facebookresearch/dlrm#132]
I'm trying to generate a torchscript model of dlrm using `torch.jot.script` method. I followed the instructions provided in this closed issue (https://github.com/facebookresearch/dlrm/issues/69) but I get the following error mentioning that `lambda` is not supported by `torch.jit`.

```
raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: Lambda aren't supported:
  File "dlrm_s_pytorch.py", line 423
            t_list.append(y)
        # adjust the list to be ordered per device
        ly = list(map(lambda y: list(y), zip(*t_list)))
                      ~ <--- HERE
        # debug prints
        # print(ly)
```

**Comment by mnaumovfb** [comment]
It's likely that you are exercising the parallel forward path, while the prior issue looked into sequential forward path.

We are not officially committed to supporting torch script in DLRM, but you can see that most of the errors are relatively straightforward, you simply need to massage the code to make it work based on the following rules https://pytorch.org/docs/stable/jit.html#creating-torchscript-code. For instance, I suspect that if you rewrite the above code with for loops rather than lambda functions it will succeed.

**Comment by nithin-nod** [comment]
Sequential path fits my use case as well. I did fix the `lambda` error with your suggestion but other issues crop up which requires further investigation. Thank you.
