### ISSUE TITLE
About DCN Settings

### ISSUE THREAD

**Issue by ShunLu91** [facebookresearch/dlrm#151]
Thanks for your nice work!
I notice that DLRM is compared with DCN in the paper. I wonder if you fix the embedding dimension as 16 for the DCN model.
(I found this sentence in the paper: "An embedding dimension of 16 is used.", but I want to ensure it.) Because the DCN model use the customized embedding dimension, which is 1026 in total. But if they are all fixed as 16, the number of embedding parameters might decrease a lot, which may affect the performance of DCN.
Great thanks and best wishes!

**Comment by mnaumovfb** [comment]
I believe @hjmshi would be the best person to answer this question. Let me ping him.

**Comment by hjmshi** [comment]
Yes, from what I recall, an embedding dimension of 16 is used for both networks. One can in fact significantly improve the performance of DLRM too if one increases the embedding size, but for fairness of comparison, we fixed the embedding dimension for both networks so that the number of parameters is approximately equal. Note that having variable embedding dimensions for different categorical features is not possible for DLRM due to the dot product interaction (at least in its simplest form).

**Comment by ShunLu91** [comment]
I aggree with you that fixing the embedding dimension as 16 for both networks is reasonable. 
Great thanks!
