### ISSUE TITLE
Embedding vs Embeddingbag

### ISSUE THREAD

**Issue by myungkeun-cho** [facebookresearch/dlrm#164]
Hi,

I'm studying about Embedding.

https://github.com/facebookresearch/dlrm/issues/63#issuecomment-602276150

I understood the above example in the embeddingbag function as follows.

Assuming that the embedding table is configured with 0 : a, 1 : b, 2 : c, 3 : d, 4 : e, 5 : f and that the embeddingbag function operates with mode=sum, the above example will work like this.

embeddingbag(lS_i, lS_o) = [a + c, a + b + f, d]

I have a question here.
In DLRM, if mini-batch is 128 then lS_o=[0, 1, 2, ..., 127] and lS_i=[index_0, index_1, index_2, ..., index_128].
If you use lS_o and lS_i above, isn't it the same as not using mode=sum in the embeddingbag function? In other words, isn't it the same function as the embedding function?

In fact, I trained by changing the embeddingbag function to the embedding function, and I was able to see that the training was going well.

I wonder why DLRM implemented it as an embeddedbag and when the mode=sum will be used.

I'm sorry, but the sentence might be weird because I'm not good at English.

Thank you for reading my post.

**Comment by mnaumovfb** [comment]
Your understanding of the embeddingbag function based on indices in the https://github.com/facebookresearch/dlrm/issues/63#issuecomment-602276150 is correct. Keep in mind that typically letters a ... f in your example are vectors. 

There exist different datasets, some with one-hot (single index) and others with multi-hot (multiple index) lookups. You are training with one-hot lookups, where pooling function sum is a no op. However, DLRM was written to support different datasets, including the ones with multi-hot lookups and that's why embeddingbag is used.

**Comment by myungkeun-cho** [comment]
I understand.

Thank you for your quick response.
