### ISSUE TITLE
Embedding lookup question

### ISSUE THREAD

**Issue by EtoDemerzel0427** [facebookresearch/dlrm#171]
Previously I read this paper of [RecNMP](https://arxiv.org/abs/1912.12953), in which the authors proposed a software-hardware codesign method, called *Table-aware packet scheduling*. This method is roughly to "prioritize scheduling NMP packets from a single batch requests to the same embedding table together". The authors argue that in this way, due to the temporal locality, the cache hit rate will increase a lot. This is done from the hardware perspective.

But if I am not wrong about the pytorch implementation, the `apply_emb` method is already doing so in software:
```python
    def apply_emb(self, lS_o, lS_i, emb_l, v_W_l):
        # WARNING: notice that we are processing the batch at once. We implicitly
        # assume that the data is laid out such that:
        # 1. each embedding is indexed with a group of sparse indices,
        #   corresponding to a single lookup
        # 2. for each embedding the lookups are further organized into a batch
        # 3. for a list of embedding tables there is a list of batched lookups
```

I notice some major maintainers of DLRM are also among the author list, so I would like to ask:
* what is the difference between these two ways? 
* If the original PyTorch implementation is already doing the same (or similar at least) thing, why would the table-aware packet scheduling have a significant gain in cache hit rate?
* How can this method benefit the online inference in the production, as queries may come one by one following some distribution like the Poisson distribution instead of in batches?

**Comment by liuke-wustl** [comment]
Hi Weiran, here are our thoughts for your questions.

**[Difference between pytorch implementation and multi-core CPU execution]**
In the baseline CPU-only platform, depending on the degree of parallelization for recommendation model inference, the parallel threads access the shared CPU cache hierarchy and DRAM memory bandwidth simultaneously, resulting in potential performance degradation from shared resource contention. This interference in the shared cache and the DRAM controller can affect the latency performance of the embedding operation.
In RecNMP design, the embedding lookups from the parallel threads bypass the CPU caches and are offloaded directly to the RecNMP DIMMs. While the shared cache interference is removed by design, the memory requests from the parallel threads can still be interleaved, causing shared memory bandwidth interference and potentially degrading RankCache hit rate. Here, table-aware scheduling helps improve data locality. 

**[Why table-aware packet scheduling gain cache hit rate]**
To clarify, the cache hit rate in RecNMP refers to the RankCache hit rate.
To retain the temporal locality in one batch for one embedding table, table-aware packet scheduling groups NMP packets belonging to one embedding’s batch from the CPU to launch together. This reduces the interference from other model inference threads.
The request batching idea (memory-side table-aware scheduling) can be similarly achieved at the application level using the PyTorch emb function. In this case, in the baseline CPU, a batch of embedding lookups needs to be performed as an atomic operation, in order to reduce the aforementioned interference from the shared on-chip resources.

**[Online inference queries]**
One recommendation inference query contains N user-item pairs for ranking, where N is the query size and larger than batch size, usually in the range of 10 to 1000. Queries can be split to multiple batches of user-item pairs where the number of user-item pairs indicate the batch size. The batches can be executed in parallel with the co-located model inference threads.

**Comment by EtoDemerzel0427** [comment]
Thank you @liuke-wustl for your detailed answer.
