### ISSUE TITLE
Save and Load Model in Caffe2 implementation

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#198]
While I see knobs to save and load models in the Pytorch implementation ```(dlrm_s_pytorch.py)```, I don't see any related knobs in ```dlrm_s_caffe2.py``` . How can I save the model and load it to do just inference in caffe2. Can you please help?

**Comment by mnaumovfb** [comment]
Unfortunately only pytorch version supports saving and loading the model, with flags `--save-model` and `--load-model` flags, respectively. You might be able to create something similar in Caffe2 using ONNX because you already have the saving of the model and loading can be done following [this code]( https://github.com/mlcommons/inference/blob/master/recommendation/dlrm/pytorch/python/backend_onnxruntime.py) in MLPerf/MLCommons.
