### ISSUE TITLE
mini-batch-size and num-batches in relation to global sample number

### ISSUE THREAD

**Issue by JasonFantl** [facebookresearch/dlrm#293]
I am trying to understand how mini-batch-size and num-batches are used when generating data, specifically how many total samples are generated. On 1 GPU I imagine you can calculate the global sample count by `mini-batch-size * num-batches`, but is that true on multiple GPUs as well? had thought that using 8 GPUs would be faster than using 1 GPU, but 8 GPUs is significantly slower. This makes me think the global number of samples is not the same when I change the number of GPUs, is this the case?

**Comment by mnaumovfb** [comment]
The following issue https://github.com/facebookresearch/dlrm/issues/128 discusses these parameters. Please let me know if it helps answer your questions.

**Comment by samiwilf** [comment]
@JasonFantl 
If you are referring to the script dlrm_s_pytorch.py and its CLI argument --mini-batch-size, then the number of GPUs will not impact calculating the global sample count, because --mini-batch-size stores the global batch size, not local batch size. However, in the TorchRec-based DLRM script torchrec_dlrm/dlrm_main.py, the CLI argument --batch_size stores the local batch size.  This is why @mnaumovfb asked which DLRM script is at issue.

**Comment by mnaumovfb** [comment]
It looks like the questions have been answered. Closing.
