### ISSUE TITLE
Use of --max-ind-range

### ISSUE THREAD

**Issue by ddkalamk** [facebookresearch/dlrm#53]
I am having an issue with using --max-ind-range arg. It is used when preprocessing dataset and if we set it to low value while training run, it produces runtime error saying index out of range. Ideally, preprocessing should not use it but training run should do the modulo operation in data loader, what do you think?

Here is an example of error. I have preprocessed terabyte dataset using 10M range. Then if I run training with --max-ind-range=1000000 (1M), it produces this run time error:

```
python dlrm_s_pytorch.py --arch-sparse-feature-size=128 --arch-mlp-bot="13-512-256-128" --arch-mlp-top="1024-1024-512-256-1" --data-generation=dataset --data-set=terabyte --raw-data-file=$HOME/dlrm_dataset/day --processed-data-file=./input/terabyte_processed.npz --loss-function=bce --round-targets=True --learning-rate=1.0 --mini-batch-size=2048 --print-freq=10 --num-batches=100 --print-time --test-freq=0 --test-mini-batch-size=16384 --test-num-workers=0 --memory-map --mlperf-logging  --max-ind-range=1000000 --numpy-rand-seed 4


time/loss/accuracy (if enabled):
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1055, in <module>
    Z = dlrm_wrap(X, lS_o, lS_i, use_gpu, device)
  File "dlrm_s_pytorch.py", line 948, in dlrm_wrap
    return dlrm(X, lS_o, lS_i)
  File "/nfs_home/ddkalamk/venv/pytsrc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in _call_
    result = self.forward(*input, **kwargs)
  File "dlrm_s_pytorch.py", line 384, in forward
    return self.sequential_forward(dense_x, lS_o, lS_i)
  File "dlrm_s_pytorch.py", line 396, in sequential_forward
    ly = self.apply_emb(lS_o, lS_i, self.emb_l)
  File "dlrm_s_pytorch.py", line 338, in apply_emb
    V = E(sparse_index_group_batch.contiguous(), sparse_offset_group_batch)
  File "/nfs_home/ddkalamk/venv/pytsrc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in _call_
    result = self.forward(*input, **kwargs)
  File "/nfs_home/ddkalamk/venv/pytsrc/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 281, in forward
    per_sample_weights)
  File "/nfs_home/ddkalamk/venv/pytsrc/lib/python3.7/site-packages/torch/nn/functional.py", line 1646, in embedding_bag
    per_sample_weights)
RuntimeError: [enforce fail at embedding_lookup_idx.cc:226] 0 <= idx && idx < data_size. Index 815 is out of bounds: 2147347, range 0 to 1000000
```

**Comment by mnaumovfb** [comment]
In principle, you should be able to run the code without specifying the --max-index-range option to create the pre-processed from raw data, and then train on the pre-processed data with or without --max-in-range, which I think is the functionality you are requesting. 

What you can not do is run pre-process with one --max-in-range and then run training with another value of the --max-ind-range. Is this the case for your error above?

The reason for it is that --max-ind-range indeed affects the pre-procesing of data. This is useful because it shrinks the size of the python dictionaries that are used to map hash values into indices for sparse features. On a machine with limited resources this could be a difference between running or not the code.

**Comment by ddkalamk** [comment]
> What you can not do is run pre-process with one --max-in-range and then run training with another value of the --max-ind-range. Is this the case for your error above?

Yes, currently there is no use of specifying --max-ind-range while doing a training run (unless one is doing preprocessing in the same run). So, behavior of --max-ind-range for training run is confusing. It should either error out at the beginning saying --max-ind-range specified is smaller than actual embedding table size in pre-processed dataset so it avoids runtime error later or modulo operation should be performed in the data loader before returning the indices. I suggest using the later option as it allows doing preprocessing on some big fat machine once and use different --max-ind-range values for training runs based on resources available.

Also, it might be helpful to save --max-ind-range used for preprocessing and dump it at the time of loading the dataset. Also, dump the actual MLP and Embedding table sizes being used under MLPerf logging option.

**Comment by mnaumovfb** [comment]
"Yes, currently there is no use of specifying --max-ind-range ..."
This is not quite true. As I explained above, it is useful to cap the dictionary sizes during pre-processing in the same run. It is also useful to cap the index range when using uncapped pre-processed data that was generated  earlier.

I do agree with you that the behavior is not ideal and can be confusing. We will think of a way to address it. Thank you for raising this issue.

**Comment by ddkalamk** [comment]
> It is also useful to cap the index range when using uncapped pre-processed data that was generated earlier.

This is not true. My example run precisely shows this problem as indices goes out of range because tables are capped at max ind range value but corresponding modulo operation is not performed on indices even if pre-processing was done uncapped or with higher max-ind-range value.

**Comment by ddkalamk** [comment]
Here is my attempt to fix this issue in dist_exp branch https://github.com/facebookresearch/dlrm/pull/55/commits/d48858dcb9ddc64e183239faab9a330ea1d7fd50

**Comment by mnaumovfb** [comment]
In short: You are correct. Your fix is reasonable, and we will adopt it.  

A more detailed long answer is given below:
(1) In the original loader the mod by --max-ind-range used to happen in __default_preprocess routine, but later the use of this routine was abandoned in favor of direct pre-processing in the collate_wrapper, where mod by --max-ind-range was not propagated. 

(2) In the mlperf loader the mod by --max-in-range also was not enforced.

This has probably gone unnoticed because it only affected cases when different --max-ind-range was used between dataset pre-processing and actual runs, which nobody seems to have exercised.

**Comment by ddkalamk** [comment]
Thank you :)

**Comment by mnaumovfb** [comment]
I have updated the code with the following commit 5d31ee1 

Please give it a try and let me know if it works for you.

**Comment by ddkalamk** [comment]
Looks good. Thank you, closing the issue.
