### ISSUE TITLE
Is there a way to avoid model parallelism in multi-gpu environment

### ISSUE THREAD

**Issue by kapilkd13** [facebookresearch/dlrm#56]
I have a model whose embedding table takes less than 2 gb in total. I have a 4 gpu system with me. When I try to run model in multi-gpu environment, it takes 20-30 percent more time per iteration compared to when I run model on a single gpu. This should not have happened. 
I am guessing that the architecture divides the embedding tables across multiple gpu, and the increased time is due to communication between these machines during butterfly shuffle. Am I right?
If yes, is there a way to copy all tables across all GPU's and make model data-parallel only. 
Am I looking at this increased iteration time correctly.

**Comment by mnaumovfb** [comment]
In your case it would probably be better to use a single GPU. You can do so by adding --use-gpu flag to the command line and setting environment variable
> CUDA_VISIBLE_DEVICES=0

With respect to using data parallelism only,
(i) The combination of model and data parallelism is designed to handle a typical scenario where large embedding tables can not be replicated due to memory constraints. 
(ii) In your case, you could indeed replicate everything (including the embeddings) and avoid the butterfly shuffle, but you would still have the overhead of performing the allreduce operation, that would be required to synchronize the weights across GPUs. 
(iii) We do not implement the approach (ii) in the current code. If you try it yourself, one difficulty to watch for is the splitting of the input mini-batch into sub-batches for the embedding layers. Notice that this input consists of offsets and indices corresponding to embedding lookups, rather than a tensor with first dimension being the mini-batch size (as is typical for convolution or fully connected layers).

**Comment by kapilkd13** [comment]
@mnaumovfb  Thanks, I will try to implement this, will make a PR if it works.
