### ISSUE TITLE
lS_o vs. lS_i

### ISSUE THREAD

**Issue by Otodea** [facebookresearch/dlrm#63]
Hi,
Sparse data is translated into the PyTorch implementation into two embeddings, lS_o and lS_i. Can you please explain how this translation from the Kaggle input data happens, and what the difference between lS_o (sparse offset) and lS_i (sparse index) is?

**Comment by mnaumovfb** [comment]
lS_o and lS_i are inputs to the [embeddingBag layer](https://pytorch.org/docs/stable/nn.html). For instance in order to represent three embedding lookups, with indices {0, 2}, {0, 1, 5} and {3} we use
lS_o = [0, 2, 5]
lS_i = [0, 2, 0, 1, 5, 3]

The dataset is composed of dense and sparse features. The latter are represented as hash values, to which an [index is associated during pre-processing stage](https://github.com/facebookresearch/dlrm/issues/58#issuecomment-590185652). This index is used to index into the embedding. In this case the lookup has a single index, so lS_o=[0] and lS_i=[index].
