### ISSUE TITLE
How is the number of rows for each embedding bag decided?

### ISSUE THREAD

**Issue by Otodea** [facebookresearch/dlrm#67]
Hi,

From my understanding, in DLRM, the number of embedding bags is the same as the number of sparse feature types. For example, for Kaggle data,  there are 26 sparse feature types and thus 26 different embedding bags.

Now, I was wondering how the number of rows for each embedding bag is decided. Is the number of rows for an embedding bag random, or is it proportional to the data size or any other factors?

Thank you!

**Comment by mnaumovfb** [comment]
Your understanding about sparse features and embedding tables is correct. 

In this dataset by default the number of rows in an embedding is based on the [unique indices that a sparse feature can attain](https://github.com/facebookresearch/dlrm/issues/58#issuecomment-590185652), so that each unique index maps to a single embedding vector. However, if the index range is too large, we can limit it with --max-ind-range parameter, the value of which is typically chosen empirically.

**Comment by Otodea** [comment]
Got it. Thanks!
