### ISSUE TITLE
Convert dlrm to torch.jit.script model

### ISSUE THREAD

**Issue by zhuhaozhe** [facebookresearch/dlrm#69]
Hi, I wanna convert DLRM to a JIT model, I find the instructions at https://pytorch.org/docs/stable/jit.html#creating-torchscript-code, follow it I add one line
" dlrm = torch.jit.script(dlrm)" after dlrm have been init, but it dosen't work. 

Error Message:
TypeError:
'int64' object for attribute 'num_embeddings' is not a valid constant.
Valid constants are:
1. a nn.ModuleList
2. a value of type {bool, float, int, str, NoneType, device, layout, dtype}
3. a list or tuple of (2)

After soving it by replacing "n = ln[i]" by "n = int(ln[i])" in function "create_emb", I got Error Message Below:

'DLRM_Net.sequential_forward' is being compiled since it was called from 'DLRM_Net.forward'
  File "dlrm_s_pytorch.py", line 288
    def forward(self, dense_x, lS_o, lS_i):
        if self.ndevices <= 1:
            return self.sequential_forward(dense_x, lS_o, lS_i)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        else:
            return self.parallel_forward(dense_x, lS_o, lS_i)

I would be grateful if there is any suggestions from you.

**Comment by mnaumovfb** [comment]
I have spent quite some time investigating this issue. There is a simple answer to why you are seeing these errors, but the fix seems to be very painful and I'll only provide it as a guideline here.

The reason why you are seeing the last error is that torchscript assumes that every argument to the function is Tensor [unless annotated otherwise](https://pytorch.org/docs/master/jit_language_reference.html#default-types): "By default, all parameters to a TorchScript function are assumed to be Tensor." Therefore, the argument "layers" to apply_mlp is interpreted as Tensor rather than a Sequential container (which is its true class/type). 

Unfortunately, only a limited number of types are supported in torchscript and they do not seem to [include layer or container types](https://pytorch.org/docs/master/jit_language_reference.html#default-types). Therefore, if you want to convert this model you must patch every function such that it has only Tensors or annotated List[Tensor] as an argument. Here is a rough patch for dlrm_s_pytorch.py file:
a. Add `from typing import Dict, List` to the imports
b. As you correctly noted cast `n = int(ln[i])` on line 142
c. Define two auxiliary functions 
```
def apply_mlp_bot(self, x):
        return self.bot_l(x)
def apply_mlp_top(self, x):
        return self.top_l(x)
```
and call them instead of `self.apply_mlp(dense_x, self.bot_l) ` on line 305 and `self.apply_mlp(z, self.top_l)` on line 320.
d. Annotate types in `def interact_features(self, x: torch.Tensor, ly: List[torch.Tensor])` on line 263
e. Replace the unsupported li and lj generation on lines 280-281, with a slight modification of the prior approach
```
offset = 0 if self.arch_interaction_itself else -1
lij = torch.tril_indices(ni, nj, offset=offset)
li = lij[0,:]
lj = lij[1,:]
```
f.  Replace `elif self.arch_interaction_op == "cat":` on line 285 with simply `else:` clause, while removing the original else clause on lines 288-293
g. The indexing of ModuleList is also not supported by torchscript, therefore in apply_emb routine replace line 248
`for k, sparse_index_group_batch in enumerate(lS_i)`
with
```
for k, E in enumerate(self.emb_l):
    sparse_index_group_batch = lS_i[k]
```
and delete line 255 `E = emb_l[k]`
i. Finally, place `dlrm = torch.jit.script(dlrm) ` on line 740 after the model setup is finalized.

I think that should do it. Please verify the result of the run with and without torchscript for correctness.

**Comment by zhuhaozhe** [comment]
HI @mnaumovfb . Thank you very much for your reply. You guideline is right and helpful. It seems torch.jit.script are strict, I must follow their rules to re-write modules like DLRMs to use this interface.  Hope it can be more flexible in the future.

Anyway,  I am very grateful for your time, thanks again.

**Comment by nithin-nod** [comment]
I followed all the steps that @mnaumovfb mentioned but get the following error:

`RuntimeError: 

apply_emb(__torch__.DLRM_Net self, Tensor lS_o, Tensor lS_i, Tensor emb_l) -> (Tensor[]):
Expected a value of type 'Tensor (inferred)' for argument 'emb_l' but instead found type '__torch__.torch.nn.modules.container.ModuleList'.
Inferred 'emb_l' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "dlrm_s_pytorch.py", line 365

        # process sparse features(using embeddings), resulting in a list of row vectors
        ly = self.apply_emb(lS_o, lS_i, self.emb_l)
             ~~~~~~~~~~~~~~ <--- HERE
        # for y in ly:
        #     print(y.detach().cpu().numpy())
'DLRM_Net.sequential_forward' is being compiled since it was called from 'DLRM_Net.forward'
  File "dlrm_s_pytorch.py", line 353
    def forward(self, dense_x, lS_o, lS_i):
        if self.ndevices <= 1:
            return self.sequential_forward(dense_x, lS_o, lS_i)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        else:
            return self.parallel_forward(dense_x, lS_o, lS_i)
`
