### ISSUE TITLE
num-indices-per-lookup-fixed for random input data

### ISSUE THREAD

**Issue by huwan** [facebookresearch/dlrm#96]
The benchmark allows number indices per lookup to be fixed by setting `--num-indices-per-lookup-fixed=True`. But for random input data, this number will be chagned in case some index duplicates were removed, making it not fixed.

https://github.com/facebookresearch/dlrm/blob/463e8d31f4182952d5be1f05fa5998e6fa7a20cf/dlrm_data_pytorch.py#L765-L774

**Comment by mnaumovfb** [comment]
Thank you for pointing it out. As a workaround you should be able to exchange lines 766-769 for a call to [random.sample](https://docs.python.org/3.8/library/random.html#random.sample), so that it looks something like this: 
```
sparse_group = np.array(random.sample(range(size), sparse_group_size)).astype(np.int64)
```

Let me know if it works for you and wether you see any overhead in terms of required memory.

**Comment by huwan** [comment]
Thanks for the workaround.
